/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QsozfI91bpJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function login() {
  const [isSignup, setIsSignup] = useState(false)
  const handleSubmit = (e) => {
    e.preventDefault()
    if (isSignup) {
      window.location.href = "/signup"
    } else {
      window.location.href = "/dashboard"
    }
  }
  return (
    <div className="grid min-h-screen grid-cols-1 lg:grid-cols-2">
      <div className="flex items-center justify-center bg-[rgb(24,60,103)] p-8 lg:p-12">
        <div className="mx-auto max-w-md space-y-6">
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-[#f1f1f1]">Welcome to Codimens</h1>
            <p className="mt-2 text-lg text-[#f1f1f1]/80">Log in to your account.</p>
          </div>
          <div className="space-y-4">
            <Button variant="outline" className="w-full text-[rgb(24,60,103)] border-[rgb(24,60,103)]">
              Log in with Google
            </Button>
            <Button variant="outline" className="w-full text-[rgb(24,60,103)] border-[rgb(24,60,103)]">
              Log in with GitHub
            </Button>
          </div>
          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <span className="w-full border-t border-[#f1f1f1]/20" />
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-[rgb(24,60,103)] px-2 text-[#f1f1f1]">Or log in with email</span>
            </div>
          </div>
          <form className="space-y-4" onSubmit={handleSubmit}>
            <div className="space-y-2">
              <Label htmlFor="email" className="text-[#f1f1f1]">
                Email
              </Label>
              <Input
                id="email"
                type="email"
                placeholder="m@example.com"
                required
                className="bg-[#f1f1f1] text-[rgb(24,60,103)]"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password" className="text-[#f1f1f1]">
                Password
              </Label>
              <Input id="password" type="password" required className="bg-[#f1f1f1] text-[rgb(24,60,103)]" />
            </div>
            <Button type="submit" className="w-full bg-[rgb(24,60,103)] text-[#f1f1f1] hover:bg-[#005d8f]">
              Log In
            </Button>
          </form>
          <div className="text-center text-[#f1f1f1]">
            <p>
              Don't have an account?{" "}
              <button type="button" onClick={() => setIsSignup(true)} className="font-medium underline">
                Sign up
              </button>
            </p>
          </div>
        </div>
      </div>
      <div className="hidden lg:flex items-center justify-center bg-[rgb(24,60,103)] p-8">
        <img
          src="/codimens.png"
          alt="Image Not found"
          width={600}
          height={600}
          className="max-w-full h-auto"
          style={{ aspectRatio: "600/600", objectFit: "cover" }}
        />
      </div>
    </div>
  )
}
